Always load a token from the environment when on TileDB Cloud
TileDB-Inc/TileDB-PyBabylonJS pull request #55
Opened 2023-04-19 18:01 UTC by MargrietGroenendijk

A token was only loaded from the env when a cloud array was loaded, this caused issues with loading models together with a point cloud from a local array or dict. This PR files this, a token is always loaded from the env when available

2023-04-19 18:04 UTC, Shelnutt2 approved these changes

2023-05-25 11:04 UTC, SarantopoulosKon requested changes

2023-05-25 11:04 UTC, SarantopoulosKon commented on package.json
> -    "@tiledb-inc/viz-core": "1.0.0"
Update to latest `alpha` 1.0.2-alpha.2

2023-05-26 12:15 UTC, SarantopoulosKon approved these changes

2023-05-26 15:02 UTC, merged